2024-02-08 20:15:12.782 | ERROR    | app.api.app_v1.endpoints.user:create_user:279 - (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`testdb`.`users`, CONSTRAINT `users_ibfk_1` FOREIGN KEY (`student_id`) REFERENCES `students` (`student_id`))')
[SQL: INSERT INTO users (username, password, `status`, jobnum, student_id, age, sex, `role`, addtime) VALUES (%(username)s, %(password)s, %(status)s, %(jobnum)s, %(student_id)s, %(age)s, %(sex)s, %(role)s, %(addtime)s)]
[parameters: {'username': 'brownlu23', 'password': '$2b$12$jQl8az5pKyKhKDNmieYYpurDVT8GswfetNcMTQQ3vg0NW11BW7CcW', 'status': 0, 'jobnum': 0, 'student_id': '2021110', 'age': 19, 'sex': 'ÄÐ', 'role': 0, 'addtime': datetime.datetime(2024, 2, 8, 19, 53, 54, 245387)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1763, in _execute_context
    self.dialect.do_execute(
    ©¦    ©¦       ©¸ <function DefaultDialect.do_execute at 0x000001FCF4A3E050>
    ©¦    ©¸ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x000001FCF561FA00>
    ©¸ <sqlalchemy.engine.base.Connection object at 0x000001FCF5DDB850>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
    ©¦      ©¦       ©¦          ©¸ {'username': 'brownlu23', 'password': '$2b$12$jQl8az5pKyKhKDNmieYYpurDVT8GswfetNcMTQQ3vg0NW11BW7CcW', 'status': 0, 'jobnum': ...
    ©¦      ©¦       ©¸ 'INSERT INTO users (username, password, `status`, jobnum, student_id, age, sex, `role`, addtime) VALUES (%(username)s, %(pass...
    ©¦      ©¸ <function Cursor.execute at 0x000001FCF56DF640>
    ©¸ <pymysql.cursors.Cursor object at 0x000001FCF5DD9CF0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
             ©¦    ©¦      ©¸ "INSERT INTO users (username, password, `status`, jobnum, student_id, age, sex, `role`, addtime) VALUES ('brownlu23', '$2b$12...
             ©¦    ©¸ <function Cursor._query at 0x000001FCF56DFAC0>
             ©¸ <pymysql.cursors.Cursor object at 0x000001FCF5DD9CF0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
    ©¦    ©¦     ©¸ "INSERT INTO users (username, password, `status`, jobnum, student_id, age, sex, `role`, addtime) VALUES ('brownlu23', '$2b$12...
    ©¦    ©¸ <function Connection.query at 0x000001FCF5726DD0>
    ©¸ <pymysql.connections.Connection object at 0x000001FCF579D330>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    ©¦    ©¦                ©¦    ©¦                             ©¸ False
    ©¦    ©¦                ©¦    ©¸ <function Connection._read_query_result at 0x000001FCF5727400>
    ©¦    ©¦                ©¸ <pymysql.connections.Connection object at 0x000001FCF579D330>
    ©¦    ©¸ 1
    ©¸ <pymysql.connections.Connection object at 0x000001FCF579D330>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
    ©¦      ©¸ <function MySQLResult.read at 0x000001FCF5727BE0>
    ©¸ <pymysql.connections.MySQLResult object at 0x000001FCF482CF70>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ©¦    ©¸ None
                   ©¸ <pymysql.connections.MySQLResult object at 0x000001FCF482CF70>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
    ©¦      ©¸ <function MysqlPacket.raise_for_error at 0x000001FCF5725630>
    ©¸ <pymysql.protocol.MysqlPacket object at 0x000001FCF5728EB0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    ©¦   ©¦                     ©¦    ©¸ <member '_data' of 'MysqlPacket' objects>
    ©¦   ©¦                     ©¸ <pymysql.protocol.MysqlPacket object at 0x000001FCF5728EB0>
    ©¦   ©¸ <function raise_mysql_exception at 0x000001FCF56DC820>
    ©¸ <module 'pymysql.err' from 'E:\\ÍøÕ¾\\web\\web\\fastapi-backend\\pythonProject\\.venv\\lib\\site-packages\\pymysql\\err.py'>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          ©¦          ©¦      ©¸ 'Cannot add or update a child row: a foreign key constraint fails (`testdb`.`users`, CONSTRAINT `users_ibfk_1` FOREIGN KEY (`...
          ©¦          ©¸ 1452
          ©¸ <class 'pymysql.err.IntegrityError'>

pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`testdb`.`users`, CONSTRAINT `users_ibfk_1` FOREIGN KEY (`student_id`) REFERENCES `students` (`student_id`))')


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "E:\python\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    ©¦    ©¸ <function Thread._bootstrap_inner at 0x000001FCF1DB6EF0>
    ©¸ <Thread(asyncio_0, started 5012)>

  File "E:\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    ©¦    ©¸ <function Thread.run at 0x000001FCF1DB6C20>
    ©¸ <Thread(asyncio_0, started 5012)>

  File "E:\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    ©¦    ©¦        ©¦    ©¦        ©¦    ©¸ {}
    ©¦    ©¦        ©¦    ©¦        ©¸ <Thread(asyncio_0, started 5012)>
    ©¦    ©¦        ©¦    ©¸ (<weakref at 0x000001FCF5E13060; to 'ThreadPoolExecutor' at 0x000001FCF5E04D00>, <_queue.SimpleQueue object at 0x000001FCF5E1...
    ©¦    ©¦        ©¸ <Thread(asyncio_0, started 5012)>
    ©¦    ©¸ <function _worker at 0x000001FCF5DE4A60>
    ©¸ <Thread(asyncio_0, started 5012)>

  File "E:\python\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    ©¦         ©¸ <function _WorkItem.run at 0x000001FCF5DE4B80>
    ©¸ <concurrent.futures.thread._WorkItem object at 0x000001FCF5E05000>

  File "E:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ©¦    ©¦   ©¦    ©¦       ©¦    ©¸ {}
             ©¦    ©¦   ©¦    ©¦       ©¸ <concurrent.futures.thread._WorkItem object at 0x000001FCF5E05000>
             ©¦    ©¦   ©¦    ©¸ (functools.partial(<function create_user at 0x000001FCF5B78940>, db=<sqlalchemy.orm.session.Session object at 0x000001FCF5E04...
             ©¦    ©¦   ©¸ <concurrent.futures.thread._WorkItem object at 0x000001FCF5E05000>
             ©¦    ©¸ <built-in method run of _contextvars.Context object at 0x000001FCF5DFA640>
             ©¸ <concurrent.futures.thread._WorkItem object at 0x000001FCF5E05000>

> File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\app\api\app_v1\endpoints\user.py", line 275, in create_user
    user = db_create_user(db=db, user=user)
           ©¦                 ©¦        ©¸ UserCreate(username='brownlu23', password='$2b$12$jQl8az5pKyKhKDNmieYYpurDVT8GswfetNcMTQQ3vg0NW11BW7CcW', role='Ñ§Éú', jobnum=0...
           ©¦                 ©¸ <sqlalchemy.orm.session.Session object at 0x000001FCF5E04FD0>
           ©¸ <function db_create_user at 0x000001FCF5835D80>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\app\crud\user.py", line 25, in db_create_user
    db.commit()  # Ìá½»±£´æµ½Êý¾Ý¿âÖÐ
    ©¦  ©¸ <function Session.commit at 0x000001FCF55AE4D0>
    ©¸ <sqlalchemy.orm.session.Session object at 0x000001FCF5E04FD0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
    ©¦    ©¦            ©¦               ©¦    ©¸ False
    ©¦    ©¦            ©¦               ©¸ <sqlalchemy.orm.session.Session object at 0x000001FCF5E04FD0>
    ©¦    ©¦            ©¸ <function SessionTransaction.commit at 0x000001FCF55AD5A0>
    ©¦    ©¸ <sqlalchemy.orm.session.SessionTransaction object at 0x000001FCF5DDAAD0>
    ©¸ <sqlalchemy.orm.session.Session object at 0x000001FCF5E04FD0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 826, in commit
    self._prepare_impl()
    ©¦    ©¸ <function SessionTransaction._prepare_impl at 0x000001FCF55AD510>
    ©¸ <sqlalchemy.orm.session.SessionTransaction object at 0x000001FCF5DDAAD0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 805, in _prepare_impl
    self.session.flush()
    ©¦    ©¦       ©¸ <function Session.flush at 0x000001FCF55B80D0>
    ©¦    ©¸ <sqlalchemy.orm.session.Session object at 0x000001FCF5E04FD0>
    ©¸ <sqlalchemy.orm.session.SessionTransaction object at 0x000001FCF5DDAAD0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 3260, in flush
    self._flush(objects)
    ©¦    ©¦      ©¸ None
    ©¦    ©¸ <function Session._flush at 0x000001FCF55B8280>
    ©¸ <sqlalchemy.orm.session.Session object at 0x000001FCF5E04FD0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 3399, in _flush
    with util.safe_reraise():
         ©¦    ©¸ <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         ©¸ <module 'sqlalchemy.util' from 'E:\\ÍøÕ¾\\web\\web\\fastapi-backend\\pythonProject\\.venv\\lib\\site-packages\\sqlalchemy\\util...

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
    ©¦      ©¸ <function raise_ at 0x000001FCF45F0C10>
    ©¸ <module 'sqlalchemy.util.compat' from 'E:\\ÍøÕ¾\\web\\web\\fastapi-backend\\pythonProject\\.venv\\lib\\site-packages\\sqlalchem...

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 3360, in _flush
    flush_context.execute()
    ©¦             ©¸ <function UOWTransaction.execute at 0x000001FCF55A2CB0>
    ©¸ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000001FCF5E060B0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 453, in execute
    rec.execute(self)
    ©¦   ©¦       ©¸ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000001FCF5E060B0>
    ©¦   ©¸ <function SaveUpdateAll.execute at 0x000001FCF55A35B0>
    ©¸ SaveUpdateAll(mapped class User->users)

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 627, in execute
    util.preloaded.orm_persistence.save_obj(
    ©¦    ©¦         ©¦               ©¸ <function save_obj at 0x000001FCF55A0A60>
    ©¦    ©¦         ©¸ <module 'sqlalchemy.orm.persistence' from 'E:\\ÍøÕ¾\\web\\web\\fastapi-backend\\pythonProject\\.venv\\lib\\site-packages\\sqlal...
    ©¦    ©¸ <sqlalchemy.util._preloaded._ModuleRegistry object at 0x000001FCF451A890>
    ©¸ <module 'sqlalchemy.util' from 'E:\\ÍøÕ¾\\web\\web\\fastapi-backend\\pythonProject\\.venv\\lib\\site-packages\\sqlalchemy\\util...

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 242, in save_obj
    _emit_insert_statements(
    ©¸ <function _emit_insert_statements at 0x000001FCF55A1090>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1219, in _emit_insert_statements
    result = connection._execute_20(
             ©¦          ©¸ <function Connection._execute_20 at 0x000001FCF4995510>
             ©¸ <sqlalchemy.engine.base.Connection object at 0x000001FCF5DDB850>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1578, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ©¦    ©¦     ©¦             ©¦               ©¸ {'compiled_cache': {(<sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x000001FCF561FA00>, ('0', <class 'sql...
           ©¦    ©¦     ©¦             ©¸ immutabledict({})
           ©¦    ©¦     ©¸ ({'jobnum': 0, 'role': 0, 'password': '$2b$12$jQl8az5pKyKhKDNmieYYpurDVT8GswfetNcMTQQ3vg0NW11BW7CcW', 'username': 'brownlu23'...
           ©¦    ©¸ <sqlalchemy.engine.base.Connection object at 0x000001FCF5DDB850>
           ©¸ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x000001FCF5E062F0>>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 320, in _execute_on_connection
    return connection._execute_clauseelement(
           ©¦          ©¸ <function Connection._execute_clauseelement at 0x000001FCF4995360>
           ©¸ <sqlalchemy.engine.base.Connection object at 0x000001FCF5DDB850>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1447, in _execute_clauseelement
    ret = self._execute_context(
          ©¦    ©¸ <function Connection._execute_context at 0x000001FCF4995630>
          ©¸ <sqlalchemy.engine.base.Connection object at 0x000001FCF5DDB850>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1806, in _execute_context
    self._handle_dbapi_exception(
    ©¦    ©¸ <function Connection._handle_dbapi_exception at 0x000001FCF49957E0>
    ©¸ <sqlalchemy.engine.base.Connection object at 0x000001FCF5DDB850>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1987, in _handle_dbapi_exception
    util.raise_(
    ©¦    ©¸ <function raise_ at 0x000001FCF45F0C10>
    ©¸ <module 'sqlalchemy.util' from 'E:\\ÍøÕ¾\\web\\web\\fastapi-backend\\pythonProject\\.venv\\lib\\site-packages\\sqlalchemy\\util...

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1763, in _execute_context
    self.dialect.do_execute(
    ©¦    ©¦       ©¸ <function DefaultDialect.do_execute at 0x000001FCF4A3E050>
    ©¦    ©¸ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x000001FCF561FA00>
    ©¸ <sqlalchemy.engine.base.Connection object at 0x000001FCF5DDB850>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
    ©¦      ©¦       ©¦          ©¸ {'username': 'brownlu23', 'password': '$2b$12$jQl8az5pKyKhKDNmieYYpurDVT8GswfetNcMTQQ3vg0NW11BW7CcW', 'status': 0, 'jobnum': ...
    ©¦      ©¦       ©¸ 'INSERT INTO users (username, password, `status`, jobnum, student_id, age, sex, `role`, addtime) VALUES (%(username)s, %(pass...
    ©¦      ©¸ <function Cursor.execute at 0x000001FCF56DF640>
    ©¸ <pymysql.cursors.Cursor object at 0x000001FCF5DD9CF0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
             ©¦    ©¦      ©¸ "INSERT INTO users (username, password, `status`, jobnum, student_id, age, sex, `role`, addtime) VALUES ('brownlu23', '$2b$12...
             ©¦    ©¸ <function Cursor._query at 0x000001FCF56DFAC0>
             ©¸ <pymysql.cursors.Cursor object at 0x000001FCF5DD9CF0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
    ©¦    ©¦     ©¸ "INSERT INTO users (username, password, `status`, jobnum, student_id, age, sex, `role`, addtime) VALUES ('brownlu23', '$2b$12...
    ©¦    ©¸ <function Connection.query at 0x000001FCF5726DD0>
    ©¸ <pymysql.connections.Connection object at 0x000001FCF579D330>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    ©¦    ©¦                ©¦    ©¦                             ©¸ False
    ©¦    ©¦                ©¦    ©¸ <function Connection._read_query_result at 0x000001FCF5727400>
    ©¦    ©¦                ©¸ <pymysql.connections.Connection object at 0x000001FCF579D330>
    ©¦    ©¸ 1
    ©¸ <pymysql.connections.Connection object at 0x000001FCF579D330>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
    ©¦      ©¸ <function MySQLResult.read at 0x000001FCF5727BE0>
    ©¸ <pymysql.connections.MySQLResult object at 0x000001FCF482CF70>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   ©¦    ©¸ None
                   ©¸ <pymysql.connections.MySQLResult object at 0x000001FCF482CF70>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
    ©¦      ©¸ <function MysqlPacket.raise_for_error at 0x000001FCF5725630>
    ©¸ <pymysql.protocol.MysqlPacket object at 0x000001FCF5728EB0>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    ©¦   ©¦                     ©¦    ©¸ <member '_data' of 'MysqlPacket' objects>
    ©¦   ©¦                     ©¸ <pymysql.protocol.MysqlPacket object at 0x000001FCF5728EB0>
    ©¦   ©¸ <function raise_mysql_exception at 0x000001FCF56DC820>
    ©¸ <module 'pymysql.err' from 'E:\\ÍøÕ¾\\web\\web\\fastapi-backend\\pythonProject\\.venv\\lib\\site-packages\\pymysql\\err.py'>

  File "E:\ÍøÕ¾\web\web\fastapi-backend\pythonProject\.venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          ©¦          ©¦      ©¸ 'Cannot add or update a child row: a foreign key constraint fails (`testdb`.`users`, CONSTRAINT `users_ibfk_1` FOREIGN KEY (`...
          ©¦          ©¸ 1452
          ©¸ <class 'pymysql.err.IntegrityError'>

sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`testdb`.`users`, CONSTRAINT `users_ibfk_1` FOREIGN KEY (`student_id`) REFERENCES `students` (`student_id`))')
[SQL: INSERT INTO users (username, password, `status`, jobnum, student_id, age, sex, `role`, addtime) VALUES (%(username)s, %(password)s, %(status)s, %(jobnum)s, %(student_id)s, %(age)s, %(sex)s, %(role)s, %(addtime)s)]
[parameters: {'username': 'brownlu23', 'password': '$2b$12$jQl8az5pKyKhKDNmieYYpurDVT8GswfetNcMTQQ3vg0NW11BW7CcW', 'status': 0, 'jobnum': 0, 'student_id': '2021110', 'age': 19, 'sex': 'ÄÐ', 'role': 0, 'addtime': datetime.datetime(2024, 2, 8, 19, 53, 54, 245387)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
2024-02-08 20:23:20.005 | INFO     | app.api.app_v1.endpoints.user:create_user:257 - ´´½¨ÓÃ»§
2024-02-08 20:23:20.614 | SUCCESS  | app.api.app_v1.endpoints.user:create_user:276 - ´´½¨ÓÃ»§³É¹¦
